version: 2
mergeable:
  - when: pull_request.*
    validate:
    - do: description
      and:
      - must_include:
        regex: 'Test plan'
        message: 'Test plan must be included'
      - must_include:
        regex: 'Goal'
        message: 'Please include the goal of the PR'
    - do: label
      must_include:
        regex: 'test plan: no'
        message: 'If no test plan is necessary, please include test plan: no label'