version: 2
mergeable:
  - when: pull_request.*
    validate:
    - do: or
      validate:
      - do: dependent
        changed:
          file: '**/*'
          required: ['HISTORY.md'] 
      - do: description
        must_include:
          regex: 'New version is not required'
          message: 'Should cut a new version or explicitly documents new version not required in description'
        must_include:
          regex: 'Testing completed successfully|Testing not required'
          message: 'Please describe how testing was done or explicitly state testing not required'
