version: 2
mergeable:
  - when: pull_request.*
    do: or
    validate:
    - do: and
      validate:
        - do: description
          must_include:
            regex: 'Test plan'
            message: 'Test plan must be included'
        - do: title
          must_exclude:
            regex: 'WIP'
            message: 'PR should not be in WIP'
    - do: description
      must_include:
        regex: 'New version not required'
        message: 'Should cut a new version or explicitly documents new version not required in description'