version: 2
mergeable:
  - when: pull_request.*
    do: dependent
    changed:
      file: '**/*'
      required: ['HISTORY.md'] 
    unless:
      - do: description
        must_include:
          regex: 'New version not required'
          message: 'Should cut a new version or explicitly documents new version not required in description'
